name: Terraform CI

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'modules/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Detect Changed Modules
      id: changes
      run: |
        git fetch origin main:refs/remotes/origin/main
        CHANGED_MODULES=$(git diff --name-only origin/main...HEAD | grep '^modules/' | cut -d'/' -f2 | sort -u)
        echo "Changed modules: $CHANGED_MODULES"
        echo "$CHANGED_MODULES" > changed_modules.txt

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: |
        while read -r module; do
          terraform -chdir="modules/$module" init
        done < changed_modules.txt

    - name: Terraform Validate
      run: |
        while read -r module; do
          terraform -chdir="modules/$module" validate
        done < changed_modules.txt

    - name: Terraform Format Check
      run: |
        while read -r module; do
          terraform -chdir="modules/$module" fmt -check
        done < changed_modules.txt

    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: v0.50.3

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run TFLint
      run: |
        while read -r module; do
          tflint --chdir="modules/$module" -f compact
        done < changed_modules.txt

    - name: Install Checkov
      run: pip install checkov    
    
    - name: Run Checkov action
      run: |
          while read -r module; do
            echo "Running Checkov on modules/$module"
            checkov --directory "modules/$module" --framework terraform --download-external-modules true
          done < changed_modules.txt

    - name: Run Checkov action
      uses: bridgecrewio/checkov-action@master
      with:
        directory: |
          while read -r module; do
            echo "modules/$module"
          done < changed_modules.txt
        framework: terraform
        download_external_modules: true


    # - name: Set up Test Matrix
    #   id: matrix-setup
    #   run: |
    #     LOCATIONS=("swedencentral" "westeurope" "northeurope")
    #     VERSIONS=("1.1.0" "1.2.0" "1.3.0")
    #     for module in $(cat changed_modules.txt); do
    #       for location in "${LOCATIONS[@]}"; do
    #         for version in "${VERSIONS[@]}"; do
    #           echo "$module $location $version" >> test_matrix.txt
    #         done
    #       done

    # - name: Run Terraform Tests
    #   run: |
    #     while IFS=" " read -r module location version; do
    #       sed 's/{{VERSION}}/'"$version"'/g; s/{{LOCATION}}/'"$location"'/g' templates/main.tftest.hcl.tpl > modules/"$module"/tests/main.tftest.hcl
    #       terraform -chdir="modules/$module" test
    #     done < test_matrix.txt
